name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          cd source
          npm install

      - name: Build Documentation
        run: |
          npx jsdoc -c jsdoc.json -d ../docs

      - name: Prepare deployment directory
        run: |
          mkdir -p deploy
          cp source/index.html deploy/index.html
          cp -r source/* deploy/
          mv docs deploy/docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: deploy
