name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout app code from main branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Copy app files to temporary directory
        run: |
          mkdir -p temp
          cp -r source/* temp/

      - name: Checkout gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Copy app files from temporary directory to gh-pages branch
        run: |
          rm -rf *
          cp -r ../temp/* ./

      - name: Commit and push changes to gh-pages branch
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update app code"
          git push origin gh-pages
