name: Linter and style
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./source
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: npm install
    - name: Run standard
      run: npx standard
