name: Unit Tests

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./source
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Setup Xvfb
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          sudo Xvfb :99 -ac &
          export DISPLAY=:99

      - name: Start local server
        run: npm start &
        env:
          CI: true

      - name: Wait for server to be ready
        run: sleep 10 # Adjust the sleep duration as necessary

      - name: Run tests
        run: npm test

      - name: Stop server
        if: success() || failure()
        run: kill $(jobs -p)
