name: Unit Tests

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./source
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: npm install
    - name: Setup Xvfb
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb
        sudo Xvfb :99 -ac &
        export DISPLAY=:99
    - name: Run tests
      run: npm test
